name: AlexUtilsMod-Revamped
main: me.alex33856.alexutilsmod.AlexUtilsModRe-vamped
version: 1.0
description: AlexUtillsMod has extra commands for your server!
author: Alex33856
commands: 
    alexutilsmod:
        description: Shows you info about alexutilsmod
        usage: /<command>
        aliases: [aum, utilsmod, alexutils, um, au]

 
        
